apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: fedora2
  namespace: test100
spec:
  dataVolumeTemplates:
    - metadata:
        name: fedora2-volume
      spec:
        source:
          pvc:
            name: fedora-e8c7861050c7
            namespace: openshift-virtualization-os-images
        storage:
          resources:
            requests:
              storage: '34087042032'
          storageClassName: nfs-storage
  instancetype:
    name: u1.medium
  preference:
    name: fedora
  running: true
  template:
    spec:
      domain:
        devices:
          disks:
            - disk:
                bus: virtio
              name: fedora2-disk
            - disk:
                bus: virtio
              name: cloudinitdisk
      volumes:
        - dataVolume:
            name: fedora2-volume
          name: fedora2-disk
        - cloudInitConfigDrive:
            userData: |
              #cloud-config
              user: fedora
              password: hne2-kh8y-99pr
              chpasswd:
                expire: false
          name: cloudinitdisk

