apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  annotations:
    k8s.v1.cni.cncf.io/resourceName: bridge.network.kubevirt.io/bridge-dev
  name: bridge-dev
  namespace: test100
spec:
  config: '{"name":"bridge-dev","type":"cnv-bridge","cniVersion":"0.3.1","bridge":"bridge-dev","macspoofchk":"true"}'
