apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    kubevirt.io: virt-launcher
    kubevirt.io/created-by: afb645fe-0a90-4dc3-984d-c79eeb94351a
    kubevirt.io/domain: fedora1
    kubevirt.io/nodeName: worker01
    vm.kubevirt.io/name: fedora1
  name: fedora1
spec:
  ports:
  - port: 22
    name: ssh
    protocol: TCP
    targetPort: 22
  - port: 80
    name: web
    protocol: TCP
    targetPort: 80
  selector:
    kubevirt.io/domain: fedora1
  type: LoadBalancer
status:
  loadBalancer: {}
