apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
  name: fedora1-web-disk1
  namespace: test100
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 15M
  storageClassName: nfs-storage
  volumeMode: Filesystem
